version: '3.9'

services:
  db:
    image: postgres:16
    container_name: PostGresDB
    environment:
      POSTGRES_USER: eren
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: toca
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  pgdata: